namespace CSharpExtensions.Tests.Kafka;

using System.Text.Json;
using CSharpExtensions.Kafka.Cli;
using Xunit;

public sealed class KafkaUpcasterGeneratorSecurityTests
{
    [Fact]
    public void ResolverDiscovery_IgnoresCommentsAndStringLiterals()
    {
        const string source = """
            // kafka.Subscribe<CommentMessageV2>(options => { options.AddUpcastChainResolver(UpcasterGenerationMode.OnlyOnce); });
            const string sample = "kafka.Subscribe<StringMessageV2>(options => { options.AddUpcastChainResolver(Repeatable); });";
            """;

        var registrations = Program.FindResolverCalls(source);

        Assert.Empty(registrations);
    }

    [Fact]
    public void ResolverDiscovery_FindsSyntaxInvocationInsideSubscribeLambda()
    {
        const string source = """
            kafka.Subscribe<Contracts.Events.PaymentChangedV3>(options =>
            {
                options.AddUpcastChainResolver(UpcasterGenerationMode.Repeatable);
            });
            """;

        var registrations = Program.FindResolverCalls(source);

        var registration = Assert.Single(registrations);
        Assert.Equal("PaymentChangedV3", registration.ModelName);
        Assert.Equal("Repeatable", registration.Mode);
    }

    [Fact]
    public void CleanGeneratedModelFiles_DeletesOnlyOwnedCurrentModelFiles()
    {
        var directory = Path.Combine(Path.GetTempPath(), $"kafka-upcaster-{Guid.NewGuid():N}");
        Directory.CreateDirectory(directory);
        try
        {
            var currentModelFile = Path.Combine(directory, "CurrentMessageV1.cs");
            var userOwnedCurrentModelFile = Path.Combine(directory, "CurrentMessageV2.cs");
            var otherModelFile = Path.Combine(directory, "OtherMessageV1.cs");
            File.WriteAllText(
                currentModelFile,
                $"// <auto-generated />{Environment.NewLine}{Program.GeneratedFileOwnershipMarker}{Environment.NewLine}");
            File.WriteAllText(userOwnedCurrentModelFile, "public sealed record CurrentMessageV2;");
            File.WriteAllText(
                otherModelFile,
                $"// <auto-generated />{Environment.NewLine}{Program.GeneratedFileOwnershipMarker}{Environment.NewLine}");

            Program.CleanGeneratedModelFiles(directory, "CurrentMessage");

            Assert.False(File.Exists(currentModelFile));
            Assert.True(File.Exists(userOwnedCurrentModelFile));
            Assert.True(File.Exists(otherModelFile));
        }
        finally
        {
            Directory.Delete(directory, recursive: true);
        }
    }

    [Fact]
    public void CleanGeneratedModelFiles_DeletesLegacyOwnedFile()
    {
        var directory = Path.Combine(Path.GetTempPath(), $"kafka-upcaster-{Guid.NewGuid():N}");
        Directory.CreateDirectory(directory);
        try
        {
            var legacyFile = Path.Combine(directory, "CurrentMessageV1.cs");
            File.WriteAllText(
                legacyFile,
                "/// Historical version auto-generated model representation of CurrentMessageV1.");

            Program.CleanGeneratedModelFiles(directory, "CurrentMessage");

            Assert.False(File.Exists(legacyFile));
        }
        finally
        {
            Directory.Delete(directory, recursive: true);
        }
    }

    [Fact]
    public void HistoricalSchemaBoundaryAcceptsSafeBoundedFields()
    {
        using var document = JsonDocument.Parse("""
            {
              "message_id": "9bc6a24b-0651-4b72-a407-93a87379f2d1",
              "occurred-at": "2026-08-02T00:00:00Z",
              "amount": 42.5
            }
            """);

        var accepted = Program.TryExtractHistoricalFields(document.RootElement, out var fields);

        Assert.True(accepted);
        Assert.Equal(3, fields.Count);
        Assert.Equal("MessageId", Program.ToPascalCase("message_id"));
        Assert.Equal("OccurredAt", Program.ToPascalCase("occurred-at"));
    }

    [Theory]
    [InlineData("name\"); public static class Injected { public static void Run() {} } //")]
    [InlineData("owner@example.com")]
    [InlineData("phone+37499123456")]
    [InlineData("field.name")]
    [InlineData("")]
    public void HistoricalSchemaBoundaryRejectsUnsafeFieldNames(string fieldName)
    {
        var json = JsonSerializer.Serialize(new Dictionary<string, object?>
        {
            [fieldName] = "value"
        });
        using var document = JsonDocument.Parse(json);

        var accepted = Program.TryExtractHistoricalFields(document.RootElement, out var fields);

        Assert.False(accepted);
        Assert.Empty(fields);
    }

    [Fact]
    public void HistoricalSchemaBoundaryRejectsGeneratedIdentifierCollisions()
    {
        using var document = JsonDocument.Parse("""
            {
              "message-id": "first",
              "message_id": "second"
            }
            """);

        var accepted = Program.TryExtractHistoricalFields(document.RootElement, out var fields);

        Assert.False(accepted);
        Assert.Empty(fields);
    }

    [Fact]
    public void CSharpLiteralEscapesUntrustedContent()
    {
        var literal = Program.CSharpStringLiteral("value\");\npublic sealed class Injected {} //");

        Assert.StartsWith("\"", literal, StringComparison.Ordinal);
        Assert.EndsWith("\"", literal, StringComparison.Ordinal);
        Assert.DoesNotContain("\npublic", literal, StringComparison.Ordinal);
        Assert.Contains("\\npublic", literal, StringComparison.Ordinal);
        Assert.Contains("\\\"", literal, StringComparison.Ordinal);
    }

    [Fact]
    public void DiscoverSchemasFromContracts_UsesVersionedSourceContractsInOrder()
    {
        var directory = Path.Combine(Path.GetTempPath(), $"kafka-contracts-{Guid.NewGuid():N}");
        Directory.CreateDirectory(directory);
        try
        {
            var v1 = Path.Combine(directory, "EventsOrdersOrderPlacedV1.cs");
            var v2 = Path.Combine(directory, "EventsOrdersOrderPlacedV2.cs");
            File.WriteAllText(v1, "namespace Contracts; public sealed record EventsOrdersOrderPlacedV1(Guid MessageId);");
            File.WriteAllText(v2, "namespace Contracts; public sealed record EventsOrdersOrderPlacedV2(Guid MessageId, decimal Amount);");

            var schemas = Program.DiscoverSchemasFromContracts(
                "EventsOrdersOrderPlacedV3",
                new[] { v2, v1 });

            Assert.Equal(2, schemas.Count);
            Assert.Single(schemas[0].Fields);
            Assert.Equal("Guid", schemas[0].Fields["messageId"]);
            Assert.Equal("decimal", schemas[1].Fields["amount"]);
        }
        finally
        {
            Directory.Delete(directory, recursive: true);
        }
    }

    [Fact]
    public void DiscoverSchemasFromContracts_RejectsOversizedSourceFile()
    {
        var directory = Path.Combine(Path.GetTempPath(), $"kafka-contracts-{Guid.NewGuid():N}");
        Directory.CreateDirectory(directory);
        try
        {
            var sourceFile = Path.Combine(directory, "OversizedV1.cs");
            File.WriteAllText(sourceFile, new string(' ', (2 * 1024 * 1024) + 1));

            Assert.Throws<InvalidOperationException>(() =>
                Program.DiscoverSchemasFromContracts("OversizedV2", new[] { sourceFile }));
        }
        finally
        {
            Directory.Delete(directory, recursive: true);
        }
    }
}
