using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace CSharpExtensions.Kafka.Cli
{
    public static class Program
    {
        private const int MaxHistoricalFields = 256;
        private const int MaxHistoricalFieldNameLength = 128;
        private const int MaxHistoricalVersions = 256;
        private const int MaxResolverRegistrations = 256;
        private const int MaxSourceFiles = 10_000;
        private const long MaxSourceFileBytes = 2L * 1024 * 1024;
        private const long MaxTotalSourceBytes = 256L * 1024 * 1024;
        private const int MaxReferencedProjects = 128;
        private const int MaxProjectReferenceDepth = 128;
        private const long MaxProjectFileBytes = 2L * 1024 * 1024;
        internal const string GeneratedFileOwnershipMarker = "// Generator: CSharpExtensions.Kafka.upcaster";
        private const string AutoGeneratedMarker = "// <auto-generated />";

        public static int Main(string[] args)
        {
            Console.WriteLine("Kafka Upcaster Chain Generator CLI started.");

            string? projectDir = null;
            string? projectFile = null;
            string? contractsDir = null;
            for (int i = 0; i < args.Length; i++)
            {
                if (args[i] == "--project-dir" && i + 1 < args.Length)
                {
                    projectDir = args[i + 1];
                }
                else if (args[i] == "--project-file" && i + 1 < args.Length)
                {
                    projectFile = args[i + 1];
                }
                else if (args[i] == "--contracts-dir" && i + 1 < args.Length)
                {
                    contractsDir = args[i + 1];
                }
            }

            if (string.IsNullOrEmpty(projectDir))
            {
                Console.Error.WriteLine("Error: --project-dir is required.");
                return 1;
            }

            try
            {
                projectDir = Path.GetFullPath(projectDir);
                if (!Directory.Exists(projectDir))
                {
                    Console.Error.WriteLine("Error: the configured project directory does not exist.");
                    return 1;
                }

                if (!TryResolveProjectFile(projectDir, projectFile, out projectFile, out var projectFileError))
                {
                    Console.Error.WriteLine($"Error: {projectFileError}");
                    return 1;
                }

                if (!string.IsNullOrWhiteSpace(contractsDir))
                {
                    contractsDir = Path.GetFullPath(contractsDir);
                    if (!Directory.Exists(contractsDir))
                    {
                        Console.Error.WriteLine("Error: the configured contracts directory does not exist.");
                        return 1;
                    }
                }

                RunGenerator(projectDir, projectFile, contractsDir);
                return 0;
            }
            catch (Exception)
            {
                Console.Error.WriteLine("Fatal Error: upcaster generation failed.");
                return 1;
            }
        }

        private static void RunGenerator(
            string projectDir,
            string projectFile,
            string? contractsDir = null)
        {
            Console.WriteLine("Scanning the configured project.");

            // 1. Scan target project files for AddUpcastChainResolver
            var csFiles = CollectSourceFiles(projectDir);

            var resolverCalls = new List<(string ModelName, string Mode, string SourceFile)>();

            foreach (var file in csFiles)
            {
                var content = ReadSourceFile(file);
                foreach (var registration in FindResolverCalls(content))
                {
                    resolverCalls.Add((registration.ModelName, registration.Mode, file));
                    if (resolverCalls.Count > MaxResolverRegistrations)
                    {
                        throw new InvalidOperationException(
                            $"The project exceeds the limit of {MaxResolverRegistrations} upcaster registrations.");
                    }

                    Console.WriteLine(
                        $"Found Subscribe<{registration.ModelName}> with AddUpcastChainResolver({registration.Mode}) in {Path.GetFileName(file)}");
                }
            }

            if (resolverCalls.Count == 0)
            {
                Console.WriteLine("No AddUpcastChainResolver registrations found in the project.");
                return;
            }

            Console.WriteLine($"Found {resolverCalls.Count} registration(s). Scanning for model definitions...");

            // Get all files in project and referenced projects
            var allAvailableCsFiles = GetAllProjectAndReferencedCsFiles(projectFile);
            if (!string.IsNullOrWhiteSpace(contractsDir))
            {
                AddSourceFiles(contractsDir, allAvailableCsFiles);
            }

            var failures = new List<string>();
            foreach (var call in resolverCalls)
            {
                try
                {
                    ProcessRegistration(
                        projectDir,
                        projectFile,
                        call.ModelName,
                        call.Mode,
                        allAvailableCsFiles);
                }
                catch (Exception)
                {
                    Console.Error.WriteLine($"Error processing model {call.ModelName}.");
                    failures.Add(call.ModelName);
                }
            }

            if (failures.Count > 0)
            {
                throw new InvalidOperationException(
                    $"Upcaster generation failed for {failures.Count} model registration(s).");
            }
        }

        internal static List<(string ModelName, string Mode)> FindResolverCalls(string source)
        {
            var root = CSharpSyntaxTree.ParseText(source).GetRoot();
            var registrations = new List<(string ModelName, string Mode)>();

            foreach (var invocation in root.DescendantNodes().OfType<InvocationExpressionSyntax>())
            {
                if (GetInvokedSimpleName(invocation.Expression) is not GenericNameSyntax subscribeName ||
                    subscribeName.Identifier.ValueText != "Subscribe" ||
                    subscribeName.TypeArgumentList.Arguments.Count != 1)
                {
                    continue;
                }

                var modelName = GetRightmostTypeIdentifier(subscribeName.TypeArgumentList.Arguments[0]);
                if (string.IsNullOrEmpty(modelName) || !SyntaxFacts.IsValidIdentifier(modelName))
                {
                    continue;
                }

                foreach (var lambda in invocation.ArgumentList.Arguments
                             .Select(argument => argument.Expression)
                             .OfType<LambdaExpressionSyntax>())
                {
                    foreach (var resolverInvocation in lambda.DescendantNodes().OfType<InvocationExpressionSyntax>())
                    {
                        var containingLambda = resolverInvocation.Ancestors()
                            .OfType<LambdaExpressionSyntax>()
                            .FirstOrDefault();
                        if (containingLambda?.Span != lambda.Span ||
                            GetInvokedSimpleName(resolverInvocation.Expression)?.Identifier.ValueText != "AddUpcastChainResolver" ||
                            resolverInvocation.ArgumentList.Arguments.Count != 1)
                        {
                            continue;
                        }

                        var mode = GetRightmostExpressionIdentifier(
                            resolverInvocation.ArgumentList.Arguments[0].Expression);
                        if (mode is "OnlyOnce" or "Repeatable")
                        {
                            registrations.Add((modelName, mode));
                        }
                    }
                }
            }

            return registrations;
        }

        private static SimpleNameSyntax? GetInvokedSimpleName(ExpressionSyntax expression)
        {
            return expression switch
            {
                MemberAccessExpressionSyntax memberAccess => memberAccess.Name,
                MemberBindingExpressionSyntax memberBinding => memberBinding.Name,
                SimpleNameSyntax simpleName => simpleName,
                _ => null
            };
        }

        private static string? GetRightmostTypeIdentifier(TypeSyntax type)
        {
            return type switch
            {
                IdentifierNameSyntax identifier => identifier.Identifier.ValueText,
                QualifiedNameSyntax qualified => qualified.Right.Identifier.ValueText,
                AliasQualifiedNameSyntax aliasQualified => aliasQualified.Name.Identifier.ValueText,
                _ => null
            };
        }

        private static string? GetRightmostExpressionIdentifier(ExpressionSyntax expression)
        {
            return expression switch
            {
                IdentifierNameSyntax identifier => identifier.Identifier.ValueText,
                MemberAccessExpressionSyntax memberAccess => memberAccess.Name.Identifier.ValueText,
                MemberBindingExpressionSyntax memberBinding => memberBinding.Name.Identifier.ValueText,
                _ => null
            };
        }

        private static bool TryResolveProjectFile(
            string projectDir,
            string? configuredProjectFile,
            out string resolvedProjectFile,
            out string error)
        {
            resolvedProjectFile = string.Empty;
            error = string.Empty;

            if (string.IsNullOrWhiteSpace(configuredProjectFile))
            {
                var candidates = Directory.EnumerateFiles(projectDir, "*.csproj", SearchOption.TopDirectoryOnly)
                    .Take(2)
                    .ToArray();
                if (candidates.Length != 1)
                {
                    error = candidates.Length == 0
                        ? "no project file was provided and the project directory contains no .csproj file."
                        : "no project file was provided and the project directory contains multiple .csproj files.";
                    return false;
                }

                resolvedProjectFile = Path.GetFullPath(candidates[0]);
                return true;
            }

            resolvedProjectFile = Path.GetFullPath(configuredProjectFile);
            if (!resolvedProjectFile.EndsWith(".csproj", StringComparison.OrdinalIgnoreCase) ||
                !File.Exists(resolvedProjectFile))
            {
                error = "the configured project file does not exist or is not a .csproj file.";
                return false;
            }

            if (!IsDescendantOrEqual(projectDir, resolvedProjectFile))
            {
                error = "the configured project file must be located inside the configured project directory.";
                return false;
            }

            return true;
        }

        private static bool IsDescendantOrEqual(string rootPath, string candidatePath)
        {
            var relativePath = Path.GetRelativePath(
                Path.GetFullPath(rootPath),
                Path.GetFullPath(candidatePath));
            return !Path.IsPathRooted(relativePath) &&
                   relativePath != ".." &&
                   !relativePath.StartsWith($"..{Path.DirectorySeparatorChar}", StringComparison.Ordinal) &&
                   !relativePath.StartsWith($"..{Path.AltDirectorySeparatorChar}", StringComparison.Ordinal);
        }

        private static List<string> GetAllProjectAndReferencedCsFiles(string projectFile)
        {
            var files = new List<string>();
            var visitedProjects = new HashSet<string>(PathComparer);
            var discoveredFiles = new HashSet<string>(PathComparer);
            long totalSourceBytes = 0;

            ScanProjectRecursively(
                projectFile,
                files,
                visitedProjects,
                discoveredFiles,
                ref totalSourceBytes,
                depth: 0);

            return files;
        }

        private static bool IsSourceFile(string path)
        {
            var excludedSegments = new[]
            {
                "bin",
                "obj",
                "upcaster-chains",
                "upcaster-resolver",
                "upcast-chains",
                "upcast-resolver"
            };
            var segments = Path.GetFullPath(path)
                .Split(new[] { Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar }, StringSplitOptions.RemoveEmptyEntries);
            return !segments.Any(segment => excludedSegments.Contains(segment, PathComparer));
        }

        private static StringComparer PathComparer { get; } =
            OperatingSystem.IsWindows() ? StringComparer.OrdinalIgnoreCase : StringComparer.Ordinal;

        private static List<string> CollectSourceFiles(string rootDirectory)
        {
            var files = new List<string>();
            var discoveredFiles = new HashSet<string>(PathComparer);
            long totalSourceBytes = 0;
            AddSourceFiles(rootDirectory, files, discoveredFiles, ref totalSourceBytes);
            return files;
        }

        private static void AddSourceFiles(string rootDirectory, List<string> files)
        {
            var discoveredFiles = new HashSet<string>(files.Select(Path.GetFullPath), PathComparer);
            long totalSourceBytes = 0;
            foreach (var file in discoveredFiles)
            {
                totalSourceBytes = checked(totalSourceBytes + GetBoundedFileLength(
                    file,
                    MaxSourceFileBytes,
                    "source file"));
            }

            if (files.Count > MaxSourceFiles || totalSourceBytes > MaxTotalSourceBytes)
            {
                throw new InvalidOperationException("The source graph exceeds the configured scan limits.");
            }

            AddSourceFiles(rootDirectory, files, discoveredFiles, ref totalSourceBytes);
        }

        private static void AddSourceFiles(
            string rootDirectory,
            List<string> files,
            HashSet<string> discoveredFiles,
            ref long totalSourceBytes)
        {
            var enumerationOptions = new EnumerationOptions
            {
                RecurseSubdirectories = true,
                AttributesToSkip = FileAttributes.ReparsePoint,
                IgnoreInaccessible = false,
                ReturnSpecialDirectories = false
            };
            foreach (var candidate in Directory.EnumerateFiles(rootDirectory, "*.cs", enumerationOptions))
            {
                if (!IsSourceFile(candidate))
                {
                    continue;
                }

                var fullPath = Path.GetFullPath(candidate);
                if (!discoveredFiles.Add(fullPath))
                {
                    continue;
                }

                if (files.Count >= MaxSourceFiles)
                {
                    throw new InvalidOperationException(
                        $"The source graph exceeds the limit of {MaxSourceFiles} files.");
                }

                var fileLength = GetBoundedFileLength(fullPath, MaxSourceFileBytes, "source file");
                if (totalSourceBytes > MaxTotalSourceBytes - fileLength)
                {
                    throw new InvalidOperationException(
                        $"The source graph exceeds the limit of {MaxTotalSourceBytes} bytes.");
                }

                totalSourceBytes += fileLength;
                files.Add(fullPath);
            }
        }

        private static long GetBoundedFileLength(string path, long maximumBytes, string fileKind)
        {
            var length = new FileInfo(path).Length;
            if (length > maximumBytes)
            {
                throw new InvalidOperationException(
                    $"A {fileKind} exceeds the limit of {maximumBytes} bytes.");
            }

            return length;
        }

        private static string ReadSourceFile(string path) =>
            ReadBoundedTextFile(path, MaxSourceFileBytes, "source file");

        private static string ReadProjectFile(string path) =>
            ReadBoundedTextFile(path, MaxProjectFileBytes, "project file");

        private static string ReadBoundedTextFile(string path, long maximumBytes, string fileKind)
        {
            using var stream = new FileStream(
                path,
                FileMode.Open,
                FileAccess.Read,
                FileShare.Read,
                bufferSize: 4096,
                FileOptions.SequentialScan);
            if (stream.Length > maximumBytes)
            {
                throw new InvalidOperationException(
                    $"A {fileKind} exceeds the limit of {maximumBytes} bytes.");
            }

            using var reader = new StreamReader(stream, Encoding.UTF8, detectEncodingFromByteOrderMarks: true);
            return reader.ReadToEnd();
        }

        private static void ScanProjectRecursively(
            string csprojPath,
            List<string> files,
            HashSet<string> visitedProjects,
            HashSet<string> discoveredFiles,
            ref long totalSourceBytes,
            int depth)
        {
            csprojPath = Path.GetFullPath(csprojPath);
            if (!File.Exists(csprojPath))
            {
                throw new InvalidOperationException("A referenced project file does not exist.");
            }

            if (!visitedProjects.Add(csprojPath))
            {
                return;
            }

            if (visitedProjects.Count > MaxReferencedProjects || depth > MaxProjectReferenceDepth)
            {
                throw new InvalidOperationException(
                    $"The project-reference graph exceeds the limit of {MaxReferencedProjects} projects or depth {MaxProjectReferenceDepth}.");
            }

            var dir = Path.GetDirectoryName(csprojPath)!;
            AddSourceFiles(dir, files, discoveredFiles, ref totalSourceBytes);

            try
            {
                var doc = XDocument.Parse(ReadProjectFile(csprojPath), LoadOptions.None);
                var projectRefs = doc.Descendants()
                    .Where(element => element.Name.LocalName == "ProjectReference")
                    .Select(x => x.Attribute("Include")?.Value)
                    .Where(v => v != null)
                    .Select(v => Path.GetFullPath(Path.Combine(dir, v!)));

                foreach (var refPath in projectRefs)
                {
                    if (File.Exists(refPath))
                    {
                        ScanProjectRecursively(
                            refPath,
                            files,
                            visitedProjects,
                            discoveredFiles,
                            ref totalSourceBytes,
                            depth + 1);
                    }
                }
            }
            catch (InvalidOperationException)
            {
                throw;
            }
            catch (Exception)
            {
                throw new InvalidOperationException("Failed to parse the project-reference graph.");
            }
        }

        private static void ProcessRegistration(
            string projectDir,
            string projectFile,
            string modelName,
            string mode,
            List<string> allCsFiles)
        {
            Console.WriteLine($"Processing upcast chain for: {modelName} (Mode: {mode})");
 
            var resolverDir = Path.Combine(projectDir, "upcast-resolver");
            var chainsDir = Path.Combine(projectDir, "upcast-chains");
            var resolverFile = Path.Combine(resolverDir, $"{modelName}UpcastResolver.cs");

            if (mode == "OnlyOnce" && File.Exists(resolverFile))
            {
                Console.WriteLine($"Resolver for {modelName} already exists and mode is OnlyOnce. Skipping generation.");
                return;
            }

            if (File.Exists(resolverFile) &&
                !IsOwnedGeneratedFile(
                    resolverFile,
                    $"/// Auto-generated schema detector and fallback resolver for {modelName}."))
            {
                throw new InvalidOperationException(
                    $"Refusing to overwrite resolver '{Path.GetFileName(resolverFile)}' because it is not owned by the generator.");
            }

            // 2. Locate model definition file and parse properties
            string? modelFilePath = null;
            string? modelFileContent = null;

            foreach (var file in allCsFiles)
            {
                var text = ReadSourceFile(file);
                if (Regex.IsMatch(text, $@"\b(class|record)\s+{modelName}\b"))
                {
                    modelFilePath = file;
                    modelFileContent = text;
                    break;
                }
            }

            if (modelFilePath == null || modelFileContent == null)
            {
                throw new Exception($"Could not find class or record definition for model '{modelName}' in the project or its references.");
            }

            var (modelNamespace, properties, topicKey) = ParseModelDetails(modelFileContent, modelName);
            Console.WriteLine($"Parsed model {modelName} in namespace {modelNamespace} with {properties.Count} properties. Topic Key: {topicKey}");

            // 3. Resolve historical schemas from versioned source contracts.
            var historicalSchemas = DiscoverSchemasFromContracts(modelName, allCsFiles);
            if (historicalSchemas.Count == 0)
            {
                throw new InvalidOperationException(
                    $"No versioned historical contracts were found for '{modelName}'. " +
                    "Reference the Contracts project or set KafkaContractsDirectory.");
            }

            // 5. Resolve target project namespace
            var projectNamespace = ResolveProjectNamespace(projectFile);

            // 6. Generate files
            Directory.CreateDirectory(resolverDir);
            Directory.CreateDirectory(chainsDir);

            // Clean only files owned by the current model registration.
            var versionedName = Regex.Match(modelName, @"^(?<base>.+)V[1-9]\d*$");
            var modelNameBase = versionedName.Success
                ? versionedName.Groups["base"].Value
                : modelName;

            CleanGeneratedModelFiles(chainsDir, modelNameBase);

            // In v2, model names no longer use the Dto suffix - use the model name directly.
            // Generate chains
            for (int i = 0; i < historicalSchemas.Count; i++)
            {
                var version = i + 1;
                var historicalModelName = $"{modelNameBase}V{version}";
                var fileContent = GenerateHistoricalModelFile(projectNamespace, historicalModelName, historicalSchemas[i]);
                var filePath = Path.Combine(chainsDir, $"{historicalModelName}.cs");
                File.WriteAllText(filePath, fileContent, Encoding.UTF8);
                Console.WriteLine($"Generated historical record: {Path.GetFileName(filePath)}");
            }

            // Generate resolver (mapping and detector)
            var resolverContent = GenerateResolverFile(projectNamespace, modelNamespace, modelName, modelNameBase, historicalSchemas, properties);
            File.WriteAllText(resolverFile, resolverContent, Encoding.UTF8);
            Console.WriteLine($"Generated upcast resolver: {Path.GetFileName(resolverFile)}");
        }

        internal static List<HistoricalSchema> DiscoverSchemasFromContracts(
            string modelName,
            IReadOnlyCollection<string> sourceFiles)
        {
            if (sourceFiles.Count > MaxSourceFiles)
            {
                throw new InvalidOperationException(
                    $"The source graph exceeds the limit of {MaxSourceFiles} files.");
            }

            var versionMatch = Regex.Match(modelName, @"^(?<base>.+)V(?<version>[1-9]\d*)$");
            if (!versionMatch.Success)
            {
                return new List<HistoricalSchema>();
            }

            var baseName = versionMatch.Groups["base"].Value;
            var currentVersion = int.Parse(
                versionMatch.Groups["version"].Value,
                System.Globalization.CultureInfo.InvariantCulture);
            if (currentVersion > MaxHistoricalVersions)
            {
                throw new InvalidOperationException(
                    $"The model exceeds the limit of {MaxHistoricalVersions} schema versions.");
            }
            var schemas = new SortedDictionary<int, HistoricalSchema>();

            foreach (var file in sourceFiles)
            {
                var content = ReadSourceFile(file);
                for (var version = 1; version < currentVersion; version++)
                {
                    var historicalName = $"{baseName}V{version}";
                    if (!Regex.IsMatch(content, $@"\b(class|record)\s+{Regex.Escape(historicalName)}\b"))
                    {
                        continue;
                    }

                    var (_, fields, _) = ParseModelDetails(content, historicalName);
                    schemas[version] = new HistoricalSchema(fields.ToDictionary(
                        field => field.CamelName,
                        field => field.Type,
                        StringComparer.Ordinal));
                }
            }

            return schemas.Values.ToList();
        }

        private static (string Namespace, List<PropertyMetadata> Properties, string TopicKey) ParseModelDetails(string fileContent, string modelName)
        {
            var syntaxTree = CSharpSyntaxTree.ParseText(fileContent);
            var root = syntaxTree.GetRoot();

            // Find Namespace
            string ns = "CSharpExtensions.MicroService";
            var namespaceNode = root.DescendantNodes().OfType<BaseNamespaceDeclarationSyntax>().FirstOrDefault();
            if (namespaceNode != null)
            {
                ns = namespaceNode.Name.ToString();
            }

            // Find class/record declaration
            TypeDeclarationSyntax? typeDecl = root.DescendantNodes().OfType<RecordDeclarationSyntax>().FirstOrDefault(r => r.Identifier.Text == modelName);
            typeDecl ??= root.DescendantNodes().OfType<ClassDeclarationSyntax>().FirstOrDefault(c => c.Identifier.Text == modelName);

            if (typeDecl == null)
            {
                throw new Exception($"Failed to parse syntax for '{modelName}'.");
            }

            // Find Topic attribute
            string topicKey = modelName;
            var topicAttr = typeDecl.AttributeLists.SelectMany(al => al.Attributes)
                .FirstOrDefault(a => a.Name.ToString().Contains("Topic"));
            
            if (topicAttr != null)
            {
                var arg = topicAttr.ArgumentList?.Arguments.FirstOrDefault();
                if (arg != null)
                {
                    var val = arg.Expression.ToString().Trim('\"', '\'');
                    if (!string.IsNullOrEmpty(val))
                    {
                        topicKey = val;
                    }
                }
            }

            var properties = new List<PropertyMetadata>();

            // Parse record primary parameters
            if (typeDecl is RecordDeclarationSyntax recordDecl && recordDecl.ParameterList != null)
            {
                foreach (var param in recordDecl.ParameterList.Parameters)
                {
                    var name = param.Identifier.Text;
                    var type = param.Type?.ToString() ?? "string";
                    properties.Add(new PropertyMetadata(name, type));
                }
            }

            // Parse properties in body
            var props = typeDecl.Members.OfType<PropertyDeclarationSyntax>();
            foreach (var prop in props)
            {
                var name = prop.Identifier.Text;
                var type = prop.Type.ToString();
                properties.Add(new PropertyMetadata(name, type));
            }

            // Deduplicate (properties declared in body might shadow parameter names)
            var uniqueProperties = properties.GroupBy(p => p.Name).Select(g => g.First()).ToList();
            if (uniqueProperties.Count > MaxHistoricalFields)
            {
                throw new InvalidOperationException(
                    $"The model exceeds the limit of {MaxHistoricalFields} properties.");
            }

            return (ns, uniqueProperties, topicKey);
        }

        internal static bool TryExtractHistoricalFields(
            JsonElement root,
            out Dictionary<string, string> fields)
        {
            fields = new Dictionary<string, string>(StringComparer.Ordinal);
            var generatedIdentifiers = new HashSet<string>(StringComparer.Ordinal);

            foreach (var property in root.EnumerateObject())
            {
                if (fields.Count >= MaxHistoricalFields ||
                    !IsSafeHistoricalFieldName(property.Name))
                {
                    fields.Clear();
                    return false;
                }

                var identifier = ToPascalCase(property.Name);
                if (!SyntaxFacts.IsValidIdentifier(identifier) ||
                    !generatedIdentifiers.Add(identifier))
                {
                    fields.Clear();
                    return false;
                }

                fields.Add(property.Name, MapJsonValueKindToType(property.Value));
            }

            return fields.Count > 0;
        }

        private static bool IsSafeHistoricalFieldName(string value)
        {
            return value.Length is > 0 and <= MaxHistoricalFieldNameLength &&
                   (IsAsciiLetter(value[0]) || value[0] == '_') &&
                   value.All(character =>
                       IsAsciiLetter(character) ||
                       char.IsAsciiDigit(character) ||
                       character is '_' or '-');
        }

        private static bool IsAsciiLetter(char value)
        {
            return value is >= 'A' and <= 'Z' or >= 'a' and <= 'z';
        }

        private static string MapJsonValueKindToType(JsonElement value)
        {
            switch (value.ValueKind)
            {
                case JsonValueKind.True:
                case JsonValueKind.False:
                    return "bool";
                case JsonValueKind.Number:
                    if (value.ToString().Contains("."))
                    {
                        return "decimal";
                    }
                    return "long";
                case JsonValueKind.String:
                    if (Guid.TryParse(value.GetString(), out _))
                    {
                        return "Guid";
                    }
                    if (DateTimeOffset.TryParse(value.GetString(), out _))
                    {
                        return "DateTimeOffset";
                    }
                    return "string";
                default:
                    return "string?";
            }
        }

        private static string GenerateHistoricalModelFile(string ns, string modelName, HistoricalSchema schema)
        {
            var sb = new StringBuilder();
            AppendGeneratedFileHeader(sb);
            sb.AppendLine($"namespace {ns}.upcast_chains;");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine();
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// Historical version auto-generated model representation of {modelName}.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine($"public sealed record {modelName}(");

            var lines = new List<string>();
            var identifiers = new HashSet<string>(StringComparer.Ordinal);
            foreach (var field in schema.Fields)
            {
                var pascalName = ToPascalCase(field.Key);
                if (!SyntaxFacts.IsValidIdentifier(pascalName) || !identifiers.Add(pascalName))
                {
                    throw new InvalidOperationException("Historical schema contains an unsafe or colliding field name.");
                }
                lines.Add($"    {field.Value} {pascalName}");
            }

            sb.Append(string.Join("," + Environment.NewLine, lines));
            sb.AppendLine();
            sb.AppendLine(");");

            return sb.ToString();
        }

        internal static string ToPascalCase(string input)
        {
            if (string.IsNullOrEmpty(input)) return string.Empty;
            var words = input.Split(new[] { '_', '-' }, StringSplitOptions.RemoveEmptyEntries);
            var result = new StringBuilder(input.Length);
            foreach (var word in words)
            {
                result.Append(char.ToUpperInvariant(word[0]));
                result.Append(word.AsSpan(1));
            }
            return result.ToString();
        }

        internal static string CSharpStringLiteral(string value)
        {
            return Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(value, quote: true);
        }

        internal static void CleanGeneratedModelFiles(string chainsDirectory, string modelName)
        {
            if (!Directory.Exists(chainsDirectory))
            {
                return;
            }

            foreach (var file in Directory.EnumerateFiles(chainsDirectory, "*.cs", SearchOption.TopDirectoryOnly))
            {
                var fileName = Path.GetFileNameWithoutExtension(file);
                if (Regex.IsMatch(fileName, $"^{Regex.Escape(modelName)}V[1-9]\\d*$") &&
                    IsOwnedGeneratedModelFile(file, fileName))
                {
                    File.Delete(file);
                }
            }
        }

        private static bool IsOwnedGeneratedModelFile(string path, string modelName)
        {
            var legacyMarker = $"/// Historical version auto-generated model representation of {modelName}.";
            return IsOwnedGeneratedFile(path, legacyMarker);
        }

        private static bool IsOwnedGeneratedFile(string path, string legacyMarker)
        {
            const int maximumHeaderCharacters = 4096;
            using var reader = new StreamReader(path, Encoding.UTF8, detectEncodingFromByteOrderMarks: true);
            var buffer = new char[maximumHeaderCharacters];
            var charactersRead = reader.ReadBlock(buffer, 0, buffer.Length);
            var header = new string(buffer, 0, charactersRead);
            return header.Contains(GeneratedFileOwnershipMarker, StringComparison.Ordinal) ||
                   header.Contains(legacyMarker, StringComparison.Ordinal);
        }

        private static void AppendGeneratedFileHeader(StringBuilder builder)
        {
            builder.AppendLine(AutoGeneratedMarker);
            builder.AppendLine(GeneratedFileOwnershipMarker);
            builder.AppendLine();
        }

        private static string ResolveProjectNamespace(string projectFile)
        {
            try
            {
                var content = ReadProjectFile(projectFile);
                var match = Regex.Match(content, @"<RootNamespace>([^<]+)</RootNamespace>");
                if (match.Success)
                {
                    return match.Groups[1].Value.Trim().Replace('-', '_');
                }
            }
            catch
            {
            }

            return Path.GetFileNameWithoutExtension(projectFile).Replace('-', '_');
        }

        private static string GenerateResolverFile(
            string projectNamespace,
            string dtoNamespace,
            string currentModelName,
            string baseModelName,
            List<HistoricalSchema> historicalSchemas,
            List<PropertyMetadata> currentProperties)
        {
            var sb = new StringBuilder();
            AppendGeneratedFileHeader(sb);
            sb.AppendLine($"namespace {projectNamespace}.upcast_resolver;");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Text.Json;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using System.Text;");
            sb.AppendLine("using System.Buffers;");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine("using CSharpExtensions.Kafka.Evolution;");
            sb.AppendLine($"using {projectNamespace}.upcast_chains;");
            if (projectNamespace != dtoNamespace)
            {
                sb.AppendLine($"using {dtoNamespace};");
            }
            sb.AppendLine();

            // 1. Generate Extension class for DI
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// Auto-generated extensions to register upcast chains for {currentModelName}.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine($"public static class {baseModelName}UpcastExtensions");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// Registers the auto-generated upcast chain and schema detector for {currentModelName}.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public static IServiceCollection Add{baseModelName}UpcastChain(this IServiceCollection services)");
            sb.AppendLine("    {");

            // Register upcasters
            for (int i = 0; i < historicalSchemas.Count; i++)
            {
                var sourceVer = i + 1;
                var targetVer = i + 2;
                var sourceVerName = $"{baseModelName}V{sourceVer}";
                var isLatest = targetVer > historicalSchemas.Count;
                var targetVerShortName = isLatest ? "Latest" : $"V{targetVer}";
                sb.AppendLine($"        services.AddSingleton<IMessageUpcaster, {sourceVerName}To{targetVerShortName}Upcaster>();");
            }

            // Register detector
            sb.AppendLine($"        services.AddSingleton<ISchemaDetector, {baseModelName}UpcastResolver>();");
            sb.AppendLine("        return services;");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();

            // 2. Generate Resolver / Detector class
            sb.AppendLine("/// <summary>");
            sb.AppendLine($"/// Auto-generated schema detector and fallback resolver for {currentModelName}.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine($"public sealed class {baseModelName}UpcastResolver : ISchemaDetector");
            sb.AppendLine("{");
            sb.AppendLine($"    public string TargetSchemaKey => {CSharpStringLiteral(currentModelName)};");
            sb.AppendLine();
            sb.AppendLine("    public bool IsTargetSchema(string rawPayloadJson)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (string.IsNullOrWhiteSpace(rawPayloadJson)) return false;");
            sb.AppendLine("        try");
            sb.AppendLine("        {");
            sb.AppendLine("            using var doc = JsonDocument.Parse(rawPayloadJson);");
            sb.AppendLine("            if (doc.RootElement.ValueKind != JsonValueKind.Object) return false;");
            sb.AppendLine();
            
            // Check if mandatory fields of current model exist (e.g. partnerId, userId)
            var currentMandatoryFields = currentProperties.Where(p => !p.IsNullable).ToList();
            foreach (var prop in currentMandatoryFields)
            {
                sb.AppendLine($"            if (!doc.RootElement.TryGetProperty({CSharpStringLiteral(prop.CamelName)}, out _) && !doc.RootElement.TryGetProperty({CSharpStringLiteral(prop.Name)}, out _)) return false;");
            }
            
            sb.AppendLine("            return true;");
            sb.AppendLine("        }");
            sb.AppendLine("        catch");
            sb.AppendLine("        {");
            sb.AppendLine("            return false;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public string? DetectSourceSchema(string rawPayloadJson)");
            sb.AppendLine("    {");
            sb.AppendLine("        if (string.IsNullOrWhiteSpace(rawPayloadJson)) return null;");
            sb.AppendLine("        try");
            sb.AppendLine("        {");
            sb.AppendLine("            using var doc = JsonDocument.Parse(rawPayloadJson);");
            sb.AppendLine("            if (doc.RootElement.ValueKind != JsonValueKind.Object) return null;");
            sb.AppendLine();

            // Scan in reverse order (or chronological) to check match
            for (int i = 0; i < historicalSchemas.Count; i++)
            {
                var keys = historicalSchemas[i].Fields.Keys;
                var sourceVerName = $"{baseModelName}V{i + 1}";
                sb.AppendLine($"            // Check match for {sourceVerName}");
                sb.Append("            if (");
                var keyChecks = new List<string>();
                foreach (var key in keys)
                {
                    keyChecks.Add($"(doc.RootElement.TryGetProperty({CSharpStringLiteral(key)}, out _) || doc.RootElement.TryGetProperty({CSharpStringLiteral(ToPascalCase(key))}, out _))");
                }
                sb.Append(string.Join(" &&" + Environment.NewLine + "                ", keyChecks));
                sb.AppendLine(")");
                sb.AppendLine("            {");
                sb.AppendLine($"                return {CSharpStringLiteral(sourceVerName)};");
                sb.AppendLine("            }");
                sb.AppendLine();
            }

            sb.AppendLine("            return null;");
            sb.AppendLine("        }");
            sb.AppendLine("        catch");
            sb.AppendLine("        {");
            sb.AppendLine("            return null;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();

            // 3. Generate Upcaster step implementations
            for (int i = 0; i < historicalSchemas.Count; i++)
            {
                var sourceVer = i + 1;
                var targetVer = i + 2;
                var sourceVerName = $"{baseModelName}V{sourceVer}";
                var isLatest = targetVer > historicalSchemas.Count;
                var targetVerName = isLatest ? currentModelName : $"{baseModelName}V{targetVer}";
                var targetVerShortName = isLatest ? "Latest" : $"V{targetVer}";

                sb.AppendLine("/// <summary>");
                sb.AppendLine($"/// Auto-generated upcaster mapping {sourceVerName} to {targetVerName}.");
                sb.AppendLine("/// </summary>");
                sb.AppendLine($"public sealed class {sourceVerName}To{targetVerShortName}Upcaster : IMessageUpcaster");
                sb.AppendLine("{");
                sb.AppendLine($"    public string SourceSchemaKey => {CSharpStringLiteral(sourceVerName)};");
                sb.AppendLine($"    public string TargetSchemaKey => {CSharpStringLiteral(targetVerName)};");
                sb.AppendLine();
                sb.AppendLine("    public string Upcast(string rawPayloadJson)");
                sb.AppendLine("    {");
                sb.AppendLine("        if (string.IsNullOrWhiteSpace(rawPayloadJson)) throw new ArgumentException(\"Payload is empty.\", nameof(rawPayloadJson));");
                sb.AppendLine();
                sb.AppendLine("        using var doc = JsonDocument.Parse(rawPayloadJson);");
                sb.AppendLine("        var root = doc.RootElement;");
                sb.AppendLine();
                sb.AppendLine("        var bufferWriter = new ArrayBufferWriter<byte>(rawPayloadJson.Length + 256);");
                sb.AppendLine("        using (var writer = new Utf8JsonWriter(bufferWriter, new JsonWriterOptions { Indented = false }))");
                sb.AppendLine("        {");
                sb.AppendLine("            writer.WriteStartObject();");
                sb.AppendLine();

                // Map fields to target schema
                var targetProps = (targetVer <= historicalSchemas.Count) 
                    ? historicalSchemas[targetVer - 1].Fields.Select(kv => new PropertyMetadata(char.ToUpper(kv.Key[0]) + kv.Key.Substring(1), kv.Value)).ToList()
                    : currentProperties;

                var sourceKeys = historicalSchemas[i].Fields.Keys.ToHashSet();

                foreach (var prop in targetProps)
                {
                    // Check if name matches directly (ignoring case and underscores)
                    var matchedKey = sourceKeys.FirstOrDefault(k => string.Equals(k.Replace("_", ""), prop.CamelName.Replace("_", ""), StringComparison.OrdinalIgnoreCase));
                    if (matchedKey != null)
                    {
                        var writeMethod = GetWriteMethodName(prop.Type);
                        sb.AppendLine($"            {writeMethod}(writer, root, {CSharpStringLiteral(prop.CamelName)}, {CSharpStringLiteral(matchedKey)});");
                    }
                    else
                    {
                        // Missing property - supply default
                        var defaultWriteCall = GetDefaultWriteCall(prop.CamelName, prop.Type);
                        sb.AppendLine($"            {defaultWriteCall}");
                    }
                }

                sb.AppendLine("            writer.WriteEndObject();");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        return Encoding.UTF8.GetString(bufferWriter.WrittenSpan);");
                sb.AppendLine("    }");
                sb.AppendLine();

                // Generate high-performance writing helpers inside each class to make it self-contained
                GenerateWriterHelpers(sb);

                sb.AppendLine("}");
                sb.AppendLine();
            }

            return sb.ToString();
        }

        private static string GetWriteMethodName(string type)
        {
            bool isNullable = type.EndsWith("?") || type.Contains("Nullable<");
            var cleanType = type.Replace("?", "").Replace("Nullable<", "").Replace(">", "").Trim();

            switch (cleanType)
            {
                case "string":
                    return "WriteStringProperty";
                case "Guid":
                    return isNullable ? "WriteNullableGuidProperty" : "WriteGuidProperty";
                case "long":
                    return isNullable ? "WriteNullableLongProperty" : "WriteLongProperty";
                case "int":
                    return isNullable ? "WriteNullableIntProperty" : "WriteIntProperty";
                case "decimal":
                    return isNullable ? "WriteNullableDecimalProperty" : "WriteDecimalProperty";
                case "bool":
                    return isNullable ? "WriteNullableBoolProperty" : "WriteBoolProperty";
                case "DateTimeOffset":
                    return isNullable ? "WriteNullableDateTimeOffsetProperty" : "WriteDateTimeOffsetProperty";
                default:
                    return "WriteStringProperty";
            }
        }

        private static string GetDefaultWriteCall(string targetKey, string type)
        {
            bool isNullable = type.EndsWith("?") || type.Contains("Nullable<");
            var targetLiteral = CSharpStringLiteral(targetKey);
            if (isNullable)
            {
                return $"writer.WriteNull({targetLiteral});";
            }

            var cleanType = type.Replace("?", "").Replace("Nullable<", "").Replace(">", "").Trim();
            switch (cleanType)
            {
                case "string":
                    return $"writer.WriteNull({targetLiteral});";
                case "Guid":
                    return $"writer.WriteString({targetLiteral}, Guid.Empty);";
                case "long":
                case "int":
                    return $"writer.WriteNumber({targetLiteral}, 0);";
                case "decimal":
                    return $"writer.WriteNumber({targetLiteral}, 0.0m);";
                case "bool":
                    return $"writer.WriteBoolean({targetLiteral}, false);";
                case "DateTimeOffset":
                    return $"writer.WriteString({targetLiteral}, DateTimeOffset.MinValue);";
                default:
                    return $"writer.WriteNull({targetLiteral});";
            }
        }

        private static void GenerateWriterHelpers(StringBuilder sb)
        {
            sb.AppendLine("    private static void WriteStringProperty(Utf8JsonWriter writer, JsonElement element, string targetKey, string sourceKey)");
            sb.AppendLine("    {");
            sb.AppendLine("        var pascalKey = char.ToUpper(sourceKey[0]) + sourceKey.Substring(1);");
            sb.AppendLine("        if (element.TryGetProperty(sourceKey, out var prop) || element.TryGetProperty(pascalKey, out prop))");
            sb.AppendLine("        {");
            sb.AppendLine("            if (prop.ValueKind == JsonValueKind.Null)");
            sb.AppendLine("                writer.WriteNull(targetKey);");
            sb.AppendLine("            else if (prop.ValueKind == JsonValueKind.String)");
            sb.AppendLine("                writer.WriteString(targetKey, prop.GetString());");
            sb.AppendLine("            else");
            sb.AppendLine("                writer.WriteString(targetKey, prop.GetRawText().Trim('\\\"'));");
            sb.AppendLine("        }");
            sb.AppendLine("        else");
            sb.AppendLine("        {");
            sb.AppendLine("            writer.WriteNull(targetKey);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    private static void WriteGuidProperty(Utf8JsonWriter writer, JsonElement element, string targetKey, string sourceKey)");
            sb.AppendLine("    {");
            sb.AppendLine("        var pascalKey = char.ToUpper(sourceKey[0]) + sourceKey.Substring(1);");
            sb.AppendLine("        if (element.TryGetProperty(sourceKey, out var prop) || element.TryGetProperty(pascalKey, out prop))");
            sb.AppendLine("        {");
            sb.AppendLine("            if (prop.ValueKind == JsonValueKind.Null)");
            sb.AppendLine("            {");
            sb.AppendLine("                writer.WriteString(targetKey, Guid.Empty);");
            sb.AppendLine("            }");
            sb.AppendLine("            else if (prop.ValueKind == JsonValueKind.String)");
            sb.AppendLine("            {");
            sb.AppendLine("                var str = prop.GetString();");
            sb.AppendLine("                writer.WriteString(targetKey, Guid.TryParse(str, out var g) ? g : Guid.Empty);");
            sb.AppendLine("            }");
            sb.AppendLine("            else");
            sb.AppendLine("            {");
            sb.AppendLine("                writer.WriteString(targetKey, Guid.Empty);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("        else");
            sb.AppendLine("        {");
            sb.AppendLine("            writer.WriteString(targetKey, Guid.Empty);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    private static void WriteNullableGuidProperty(Utf8JsonWriter writer, JsonElement element, string targetKey, string sourceKey)");
            sb.AppendLine("    {");
            sb.AppendLine("        var pascalKey = char.ToUpper(sourceKey[0]) + sourceKey.Substring(1);");
            sb.AppendLine("        if (element.TryGetProperty(sourceKey, out var prop) || element.TryGetProperty(pascalKey, out prop))");
            sb.AppendLine("        {");
            sb.AppendLine("            if (prop.ValueKind == JsonValueKind.Null)");
            sb.AppendLine("            {");
            sb.AppendLine("                writer.WriteNull(targetKey);");
            sb.AppendLine("            }");
            sb.AppendLine("            else if (prop.ValueKind == JsonValueKind.String)");
            sb.AppendLine("            {");
            sb.AppendLine("                var str = prop.GetString();");
            sb.AppendLine("                if (Guid.TryParse(str, out var g))");
            sb.AppendLine("                    writer.WriteString(targetKey, g);");
            sb.AppendLine("                else");
            sb.AppendLine("                    writer.WriteNull(targetKey);");
            sb.AppendLine("            }");
            sb.AppendLine("            else");
            sb.AppendLine("            {");
            sb.AppendLine("                writer.WriteNull(targetKey);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("        else");
            sb.AppendLine("        {");
            sb.AppendLine("            writer.WriteNull(targetKey);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    private static void WriteLongProperty(Utf8JsonWriter writer, JsonElement element, string targetKey, string sourceKey)");
            sb.AppendLine("    {");
            sb.AppendLine("        var pascalKey = char.ToUpper(sourceKey[0]) + sourceKey.Substring(1);");
            sb.AppendLine("        if (element.TryGetProperty(sourceKey, out var prop) || element.TryGetProperty(pascalKey, out prop))");
            sb.AppendLine("        {");
            sb.AppendLine("            if (prop.ValueKind == JsonValueKind.Number && prop.TryGetInt64(out var val))");
            sb.AppendLine("                writer.WriteNumber(targetKey, val);");
            sb.AppendLine("            else if (prop.ValueKind == JsonValueKind.String && long.TryParse(prop.GetString(), out var parsed))");
            sb.AppendLine("                writer.WriteNumber(targetKey, parsed);");
            sb.AppendLine("            else");
            sb.AppendLine("                writer.WriteNumber(targetKey, 0L);");
            sb.AppendLine("        }");
            sb.AppendLine("        else");
            sb.AppendLine("        {");
            sb.AppendLine("            writer.WriteNumber(targetKey, 0L);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    private static void WriteNullableLongProperty(Utf8JsonWriter writer, JsonElement element, string targetKey, string sourceKey)");
            sb.AppendLine("    {");
            sb.AppendLine("        var pascalKey = char.ToUpper(sourceKey[0]) + sourceKey.Substring(1);");
            sb.AppendLine("        if (element.TryGetProperty(sourceKey, out var prop) || element.TryGetProperty(pascalKey, out prop))");
            sb.AppendLine("        {");
            sb.AppendLine("            if (prop.ValueKind == JsonValueKind.Null)");
            sb.AppendLine("                writer.WriteNull(targetKey);");
            sb.AppendLine("            else if (prop.ValueKind == JsonValueKind.Number && prop.TryGetInt64(out var val))");
            sb.AppendLine("                writer.WriteNumber(targetKey, val);");
            sb.AppendLine("            else if (prop.ValueKind == JsonValueKind.String && long.TryParse(prop.GetString(), out var parsed))");
            sb.AppendLine("                writer.WriteNumber(targetKey, parsed);");
            sb.AppendLine("            else");
            sb.AppendLine("                writer.WriteNull(targetKey);");
            sb.AppendLine("        }");
            sb.AppendLine("        else");
            sb.AppendLine("        {");
            sb.AppendLine("            writer.WriteNull(targetKey);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    private static void WriteIntProperty(Utf8JsonWriter writer, JsonElement element, string targetKey, string sourceKey)");
            sb.AppendLine("    {");
            sb.AppendLine("        var pascalKey = char.ToUpper(sourceKey[0]) + sourceKey.Substring(1);");
            sb.AppendLine("        if (element.TryGetProperty(sourceKey, out var prop) || element.TryGetProperty(pascalKey, out prop))");
            sb.AppendLine("        {");
            sb.AppendLine("            if (prop.ValueKind == JsonValueKind.Number && prop.TryGetInt32(out var val))");
            sb.AppendLine("                writer.WriteNumber(targetKey, val);");
            sb.AppendLine("            else if (prop.ValueKind == JsonValueKind.String && int.TryParse(prop.GetString(), out var parsed))");
            sb.AppendLine("                writer.WriteNumber(targetKey, parsed);");
            sb.AppendLine("            else");
            sb.AppendLine("                writer.WriteNumber(targetKey, 0);");
            sb.AppendLine("        }");
            sb.AppendLine("        else");
            sb.AppendLine("        {");
            sb.AppendLine("            writer.WriteNumber(targetKey, 0);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    private static void WriteNullableIntProperty(Utf8JsonWriter writer, JsonElement element, string targetKey, string sourceKey)");
            sb.AppendLine("    {");
            sb.AppendLine("        var pascalKey = char.ToUpper(sourceKey[0]) + sourceKey.Substring(1);");
            sb.AppendLine("        if (element.TryGetProperty(sourceKey, out var prop) || element.TryGetProperty(pascalKey, out prop))");
            sb.AppendLine("        {");
            sb.AppendLine("            if (prop.ValueKind == JsonValueKind.Null)");
            sb.AppendLine("                writer.WriteNull(targetKey);");
            sb.AppendLine("            else if (prop.ValueKind == JsonValueKind.Number && prop.TryGetInt32(out var val))");
            sb.AppendLine("                writer.WriteNumber(targetKey, val);");
            sb.AppendLine("            else if (prop.ValueKind == JsonValueKind.String && int.TryParse(prop.GetString(), out var parsed))");
            sb.AppendLine("                writer.WriteNumber(targetKey, parsed);");
            sb.AppendLine("            else");
            sb.AppendLine("                writer.WriteNull(targetKey);");
            sb.AppendLine("        }");
            sb.AppendLine("        else");
            sb.AppendLine("        {");
            sb.AppendLine("            writer.WriteNull(targetKey);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    private static void WriteDecimalProperty(Utf8JsonWriter writer, JsonElement element, string targetKey, string sourceKey)");
            sb.AppendLine("    {");
            sb.AppendLine("        var pascalKey = char.ToUpper(sourceKey[0]) + sourceKey.Substring(1);");
            sb.AppendLine("        if (element.TryGetProperty(sourceKey, out var prop) || element.TryGetProperty(pascalKey, out prop))");
            sb.AppendLine("        {");
            sb.AppendLine("            if (prop.ValueKind == JsonValueKind.Number && prop.TryGetDecimal(out var val))");
            sb.AppendLine("                writer.WriteNumber(targetKey, val);");
            sb.AppendLine("            else if (prop.ValueKind == JsonValueKind.String && decimal.TryParse(prop.GetString(), System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, out var parsed))");
            sb.AppendLine("                writer.WriteNumber(targetKey, parsed);");
            sb.AppendLine("            else");
            sb.AppendLine("                writer.WriteNumber(targetKey, 0.0m);");
            sb.AppendLine("        }");
            sb.AppendLine("        else");
            sb.AppendLine("        {");
            sb.AppendLine("            writer.WriteNumber(targetKey, 0.0m);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    private static void WriteNullableDecimalProperty(Utf8JsonWriter writer, JsonElement element, string targetKey, string sourceKey)");
            sb.AppendLine("    {");
            sb.AppendLine("        var pascalKey = char.ToUpper(sourceKey[0]) + sourceKey.Substring(1);");
            sb.AppendLine("        if (element.TryGetProperty(sourceKey, out var prop) || element.TryGetProperty(pascalKey, out prop))");
            sb.AppendLine("        {");
            sb.AppendLine("            if (prop.ValueKind == JsonValueKind.Null)");
            sb.AppendLine("                writer.WriteNull(targetKey);");
            sb.AppendLine("            else if (prop.ValueKind == JsonValueKind.Number && prop.TryGetDecimal(out var val))");
            sb.AppendLine("                writer.WriteNumber(targetKey, val);");
            sb.AppendLine("            else if (prop.ValueKind == JsonValueKind.String && decimal.TryParse(prop.GetString(), System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, out var parsed))");
            sb.AppendLine("                writer.WriteNumber(targetKey, parsed);");
            sb.AppendLine("            else");
            sb.AppendLine("                writer.WriteNull(targetKey);");
            sb.AppendLine("        }");
            sb.AppendLine("        else");
            sb.AppendLine("        {");
            sb.AppendLine("            writer.WriteNull(targetKey);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    private static void WriteBoolProperty(Utf8JsonWriter writer, JsonElement element, string targetKey, string sourceKey)");
            sb.AppendLine("    {");
            sb.AppendLine("        var pascalKey = char.ToUpper(sourceKey[0]) + sourceKey.Substring(1);");
            sb.AppendLine("        if (element.TryGetProperty(sourceKey, out var prop) || element.TryGetProperty(pascalKey, out prop))");
            sb.AppendLine("        {");
            sb.AppendLine("            if (prop.ValueKind == JsonValueKind.True || prop.ValueKind == JsonValueKind.False)");
            sb.AppendLine("                writer.WriteBoolean(targetKey, prop.GetBoolean());");
            sb.AppendLine("            else if (prop.ValueKind == JsonValueKind.String && bool.TryParse(prop.GetString(), out var parsed))");
            sb.AppendLine("                writer.WriteBoolean(targetKey, parsed);");
            sb.AppendLine("            else if (prop.ValueKind == JsonValueKind.Number && prop.TryGetInt32(out var val))");
            sb.AppendLine("                writer.WriteBoolean(targetKey, val != 0);");
            sb.AppendLine("            else");
            sb.AppendLine("                writer.WriteBoolean(targetKey, false);");
            sb.AppendLine("        }");
            sb.AppendLine("        else");
            sb.AppendLine("        {");
            sb.AppendLine("            writer.WriteBoolean(targetKey, false);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    private static void WriteNullableBoolProperty(Utf8JsonWriter writer, JsonElement element, string targetKey, string sourceKey)");
            sb.AppendLine("    {");
            sb.AppendLine("        var pascalKey = char.ToUpper(sourceKey[0]) + sourceKey.Substring(1);");
            sb.AppendLine("        if (element.TryGetProperty(sourceKey, out var prop) || element.TryGetProperty(pascalKey, out prop))");
            sb.AppendLine("        {");
            sb.AppendLine("            if (prop.ValueKind == JsonValueKind.Null)");
            sb.AppendLine("                writer.WriteNull(targetKey);");
            sb.AppendLine("            else if (prop.ValueKind == JsonValueKind.True || prop.ValueKind == JsonValueKind.False)");
            sb.AppendLine("                writer.WriteBoolean(targetKey, prop.GetBoolean());");
            sb.AppendLine("            else if (prop.ValueKind == JsonValueKind.String && bool.TryParse(prop.GetString(), out var parsed))");
            sb.AppendLine("                writer.WriteBoolean(targetKey, parsed);");
            sb.AppendLine("            else if (prop.ValueKind == JsonValueKind.Number && prop.TryGetInt32(out var val))");
            sb.AppendLine("                writer.WriteBoolean(targetKey, val != 0);");
            sb.AppendLine("            else");
            sb.AppendLine("                writer.WriteNull(targetKey);");
            sb.AppendLine("        }");
            sb.AppendLine("        else");
            sb.AppendLine("        {");
            sb.AppendLine("            writer.WriteNull(targetKey);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    private static void WriteDateTimeOffsetProperty(Utf8JsonWriter writer, JsonElement element, string targetKey, string sourceKey)");
            sb.AppendLine("    {");
            sb.AppendLine("        var pascalKey = char.ToUpper(sourceKey[0]) + sourceKey.Substring(1);");
            sb.AppendLine("        if (element.TryGetProperty(sourceKey, out var prop) || element.TryGetProperty(pascalKey, out prop))");
            sb.AppendLine("        {");
            sb.AppendLine("            if (prop.ValueKind == JsonValueKind.String && DateTimeOffset.TryParse(prop.GetString(), out var dto))");
            sb.AppendLine("                writer.WriteString(targetKey, dto);");
            sb.AppendLine("            else");
            sb.AppendLine("                writer.WriteString(targetKey, DateTimeOffset.MinValue);");
            sb.AppendLine("        }");
            sb.AppendLine("        else");
            sb.AppendLine("        {");
            sb.AppendLine("            writer.WriteString(targetKey, DateTimeOffset.MinValue);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    private static void WriteNullableDateTimeOffsetProperty(Utf8JsonWriter writer, JsonElement element, string targetKey, string sourceKey)");
            sb.AppendLine("    {");
            sb.AppendLine("        var pascalKey = char.ToUpper(sourceKey[0]) + sourceKey.Substring(1);");
            sb.AppendLine("        if (element.TryGetProperty(sourceKey, out var prop) || element.TryGetProperty(pascalKey, out prop))");
            sb.AppendLine("        {");
            sb.AppendLine("            if (prop.ValueKind == JsonValueKind.Null)");
            sb.AppendLine("                writer.WriteNull(targetKey);");
            sb.AppendLine("            else if (prop.ValueKind == JsonValueKind.String && DateTimeOffset.TryParse(prop.GetString(), out var dto))");
            sb.AppendLine("                writer.WriteString(targetKey, dto);");
            sb.AppendLine("            else");
            sb.AppendLine("                writer.WriteNull(targetKey);");
            sb.AppendLine("        }");
            sb.AppendLine("        else");
            sb.AppendLine("        {");
            sb.AppendLine("            writer.WriteNull(targetKey);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private static string GetDefaultValueLiteral(string type)
        {
            if (type.EndsWith("?")) return "null";
            switch (type)
            {
                case "string": return "null";
                case "int": return "0";
                case "long": return "0L";
                case "decimal": return "0.0m";
                case "bool": return "false";
                case "Guid": return "Guid.Empty";
                case "DateTimeOffset": return "DateTimeOffset.MinValue";
                default: return "default";
            }
        }
    }

    public sealed class HistoricalSchema
    {
        public Dictionary<string, string> Fields { get; }

        public HistoricalSchema(Dictionary<string, string> fields)
        {
            Fields = fields;
        }
    }

    public sealed class PropertyMetadata
    {
        public string Name { get; }
        public string Type { get; }
        public string CamelName { get; }
        public bool IsNullable { get; }

        public PropertyMetadata(string name, string type)
        {
            Name = name;
            Type = type;
            CamelName = char.ToLower(name[0]) + name.Substring(1);
            IsNullable = type.EndsWith("?") || type.Contains("Nullable<");
        }
    }
}
